// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

public partial class categories
{
    [Key]
    public short category_id { get; set; }

    [Required]
    [StringLength(15)]
    public string category_name { get; set; }

    public string description { get; set; }

    public byte[] picture { get; set; }

    [InverseProperty("category")]
    public virtual ICollection<products> products { get; set; } = new List<products>();
}