// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

public partial class customer_demographics
{
    [Key]
    [StringLength(5)]
    public string customer_type_id { get; set; }

    public string customer_desc { get; set; }

    [ForeignKey("customer_type_id")]
    [InverseProperty("customer_type")]
    public virtual ICollection<customers> customer { get; set; } = new List<customers>();
}