// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

public partial class customers
{
    [Key]
    [StringLength(5)]
    public string customer_id { get; set; }

    [Required]
    [StringLength(40)]
    public string company_name { get; set; }

    [StringLength(30)]
    public string contact_name { get; set; }

    [StringLength(30)]
    public string contact_title { get; set; }

    [StringLength(60)]
    public string address { get; set; }

    [StringLength(15)]
    public string city { get; set; }

    [StringLength(15)]
    public string region { get; set; }

    [StringLength(10)]
    public string postal_code { get; set; }

    [StringLength(15)]
    public string country { get; set; }

    [StringLength(24)]
    public string phone { get; set; }

    [StringLength(24)]
    public string fax { get; set; }

    [InverseProperty("customer")]
    public virtual ICollection<orders> orders { get; set; } = new List<orders>();

    [ForeignKey("customer_id")]
    [InverseProperty("customer")]
    public virtual ICollection<customer_demographics> customer_type { get; set; } = new List<customer_demographics>();
}