// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

public partial class employees
{
    [Key]
    public short employee_id { get; set; }

    [Required]
    [StringLength(20)]
    public string last_name { get; set; }

    [Required]
    [StringLength(10)]
    public string first_name { get; set; }

    [StringLength(30)]
    public string title { get; set; }

    [StringLength(25)]
    public string title_of_courtesy { get; set; }

    public DateOnly? birth_date { get; set; }

    public DateOnly? hire_date { get; set; }

    [StringLength(60)]
    public string address { get; set; }

    [StringLength(15)]
    public string city { get; set; }

    [StringLength(15)]
    public string region { get; set; }

    [StringLength(10)]
    public string postal_code { get; set; }

    [StringLength(15)]
    public string country { get; set; }

    [StringLength(24)]
    public string home_phone { get; set; }

    [StringLength(4)]
    public string extension { get; set; }

    public byte[] photo { get; set; }

    public string notes { get; set; }

    public short? reports_to { get; set; }

    [StringLength(255)]
    public string photo_path { get; set; }

    [InverseProperty("reports_toNavigation")]
    public virtual ICollection<employees> Inversereports_toNavigation { get; set; } = new List<employees>();

    [InverseProperty("employee")]
    public virtual ICollection<orders> orders { get; set; } = new List<orders>();

    [ForeignKey("reports_to")]
    [InverseProperty("Inversereports_toNavigation")]
    public virtual employees reports_toNavigation { get; set; }

    [ForeignKey("employee_id")]
    [InverseProperty("employee")]
    public virtual ICollection<territories> territory { get; set; } = new List<territories>();
}