// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NpgsqlTypes;

namespace aspnetcoreapi10.Entities;

public partial class employment
{
    [Key]
    public int id { get; set; }

    [StringLength(20)]
    public string employee { get; set; }

    public NpgsqlRange<DateOnly>? period { get; set; }
}