// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

public partial class northwindContext : DbContext
{
    public northwindContext()
    {
    }

    public northwindContext(DbContextOptions<northwindContext> options)
        : base(options)
    {
    }

    public virtual DbSet<categories> categories { get; set; }

    public virtual DbSet<customer_demographics> customer_demographics { get; set; }

    public virtual DbSet<customers> customers { get; set; }

    public virtual DbSet<employees> employees { get; set; }

    public virtual DbSet<employment> employment { get; set; }

    public virtual DbSet<order_details> order_details { get; set; }

    public virtual DbSet<orders> orders { get; set; }

    public virtual DbSet<products> products { get; set; }

    public virtual DbSet<region> region { get; set; }

    public virtual DbSet<shippers> shippers { get; set; }

    public virtual DbSet<suppliers> suppliers { get; set; }

    public virtual DbSet<territories> territories { get; set; }

    public virtual DbSet<us_states> us_states { get; set; }

    public virtual DbSet<userauths> userauths { get; set; }

    public virtual DbSet<users> users { get; set; }

    public virtual DbSet<users0> users0 { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseNpgsql("Username=postgres;Persist Security Info=True;Password=Iamsmart27!;Database=northwind;Host=localhost");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<categories>(entity =>
        {
            entity.HasKey(e => e.category_id).HasName("pk_categories");

            entity.Property(e => e.category_id).ValueGeneratedNever();
        });

        modelBuilder.Entity<customer_demographics>(entity =>
        {
            entity.HasKey(e => e.customer_type_id).HasName("pk_customer_demographics");
        });

        modelBuilder.Entity<customers>(entity =>
        {
            entity.HasKey(e => e.customer_id).HasName("pk_customers");

            entity.HasMany(d => d.customer_type).WithMany(p => p.customer)
                .UsingEntity<Dictionary<string, object>>(
                    "customer_customer_demo",
                    r => r.HasOne<customer_demographics>().WithMany()
                        .HasForeignKey("customer_type_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_customer_customer_demo_customer_demographics"),
                    l => l.HasOne<customers>().WithMany()
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_customer_customer_demo_customers"),
                    j =>
                    {
                        j.HasKey("customer_id", "customer_type_id").HasName("pk_customer_customer_demo");
                        j.IndexerProperty<string>("customer_id").HasMaxLength(5);
                        j.IndexerProperty<string>("customer_type_id").HasMaxLength(5);
                    });
        });

        modelBuilder.Entity<employees>(entity =>
        {
            entity.HasKey(e => e.employee_id).HasName("pk_employees");

            entity.Property(e => e.employee_id).ValueGeneratedNever();

            entity.HasOne(d => d.reports_toNavigation).WithMany(p => p.Inversereports_toNavigation).HasConstraintName("fk_employees_employees");

            entity.HasMany(d => d.territory).WithMany(p => p.employee)
                .UsingEntity<Dictionary<string, object>>(
                    "employee_territories",
                    r => r.HasOne<territories>().WithMany()
                        .HasForeignKey("territory_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_employee_territories_territories"),
                    l => l.HasOne<employees>().WithMany()
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_employee_territories_employees"),
                    j =>
                    {
                        j.HasKey("employee_id", "territory_id").HasName("pk_employee_territories");
                        j.IndexerProperty<string>("territory_id").HasMaxLength(20);
                    });
        });

        modelBuilder.Entity<employment>(entity =>
        {
            entity.HasKey(e => e.id).HasName("employment_pkey");

            entity.HasIndex(e => e.period, "ix_employment_period").HasMethod("gist");
        });

        modelBuilder.Entity<order_details>(entity =>
        {
            entity.HasKey(e => new { e.order_id, e.product_id }).HasName("pk_order_details");

            entity.HasOne(d => d.order).WithMany(p => p.order_details)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_order_details_orders");

            entity.HasOne(d => d.product).WithMany(p => p.order_details)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_order_details_products");
        });

        modelBuilder.Entity<orders>(entity =>
        {
            entity.HasKey(e => e.order_id).HasName("pk_orders");

            entity.Property(e => e.order_id).ValueGeneratedNever();

            entity.HasOne(d => d.customer).WithMany(p => p.orders).HasConstraintName("fk_orders_customers");

            entity.HasOne(d => d.employee).WithMany(p => p.orders).HasConstraintName("fk_orders_employees");

            entity.HasOne(d => d.ship_viaNavigation).WithMany(p => p.orders).HasConstraintName("fk_orders_shippers");
        });

        modelBuilder.Entity<products>(entity =>
        {
            entity.HasKey(e => e.product_id).HasName("pk_products");

            entity.Property(e => e.product_id).ValueGeneratedNever();

            entity.HasOne(d => d.category).WithMany(p => p.products).HasConstraintName("fk_products_categories");

            entity.HasOne(d => d.supplier).WithMany(p => p.products).HasConstraintName("fk_products_suppliers");
        });

        modelBuilder.Entity<region>(entity =>
        {
            entity.HasKey(e => e.region_id).HasName("pk_region");

            entity.Property(e => e.region_id).ValueGeneratedNever();
        });

        modelBuilder.Entity<shippers>(entity =>
        {
            entity.HasKey(e => e.shipper_id).HasName("pk_shippers");

            entity.Property(e => e.shipper_id).ValueGeneratedNever();
        });

        modelBuilder.Entity<suppliers>(entity =>
        {
            entity.HasKey(e => e.supplier_id).HasName("pk_suppliers");

            entity.Property(e => e.supplier_id).ValueGeneratedNever();
        });

        modelBuilder.Entity<territories>(entity =>
        {
            entity.HasKey(e => e.territory_id).HasName("pk_territories");

            entity.HasOne(d => d.region).WithMany(p => p.territories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_territories_region");
        });

        modelBuilder.Entity<us_states>(entity =>
        {
            entity.HasKey(e => e.state_id).HasName("pk_usstates");

            entity.Property(e => e.state_id).ValueGeneratedNever();
        });

        modelBuilder.Entity<userauths>(entity =>
        {
            entity.HasKey(e => e.id).HasName("userauths_pkey");

            entity.Property(e => e.active).HasDefaultValue(false);
            entity.Property(e => e.addedby).HasDefaultValueSql("CURRENT_USER");
            entity.Property(e => e.addedon).HasDefaultValueSql("CURRENT_TIMESTAMP");
        });

        modelBuilder.Entity<users>(entity =>
        {
            entity.HasKey(e => e.id).HasName("users_pkey1");

            entity.Property(e => e.id).HasDefaultValueSql("nextval('users_id_seq1'::regclass)");
            entity.Property(e => e.addedat).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.addedby).HasDefaultValueSql("CURRENT_USER");
            entity.Property(e => e.status).HasDefaultValue(false);
        });

        modelBuilder.Entity<users0>(entity =>
        {
            entity.HasKey(e => e.id).HasName("users_pkey");

            entity.Property(e => e.id).HasDefaultValueSql("nextval('users_id_seq'::regclass)");
        });
        modelBuilder.HasSequence("users_seq");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}