// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

[PrimaryKey("order_id", "product_id")]
public partial class order_details
{
    [Key]
    public short order_id { get; set; }

    [Key]
    public short product_id { get; set; }

    public float unit_price { get; set; }

    public short quantity { get; set; }

    public float discount { get; set; }

    [ForeignKey("order_id")]
    [InverseProperty("order_details")]
    public virtual orders order { get; set; }

    [ForeignKey("product_id")]
    [InverseProperty("order_details")]
    public virtual products product { get; set; }
}