// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

public partial class orders
{
    [Key]
    public short order_id { get; set; }

    [StringLength(5)]
    public string customer_id { get; set; }

    public short? employee_id { get; set; }

    public DateOnly? order_date { get; set; }

    public DateOnly? required_date { get; set; }

    public DateOnly? shipped_date { get; set; }

    public short? ship_via { get; set; }

    public float? freight { get; set; }

    [StringLength(40)]
    public string ship_name { get; set; }

    [StringLength(60)]
    public string ship_address { get; set; }

    [StringLength(15)]
    public string ship_city { get; set; }

    [StringLength(15)]
    public string ship_region { get; set; }

    [StringLength(10)]
    public string ship_postal_code { get; set; }

    [StringLength(15)]
    public string ship_country { get; set; }

    [ForeignKey("customer_id")]
    [InverseProperty("orders")]
    public virtual customers customer { get; set; }

    [ForeignKey("employee_id")]
    [InverseProperty("orders")]
    public virtual employees employee { get; set; }

    [InverseProperty("order")]
    public virtual ICollection<order_details> order_details { get; set; } = new List<order_details>();

    [ForeignKey("ship_via")]
    [InverseProperty("orders")]
    public virtual shippers ship_viaNavigation { get; set; }
}