// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

public partial class products
{
    [Key]
    public short product_id { get; set; }

    [Required]
    [StringLength(40)]
    public string product_name { get; set; }

    public short? supplier_id { get; set; }

    public short? category_id { get; set; }

    [StringLength(20)]
    public string quantity_per_unit { get; set; }

    public float? unit_price { get; set; }

    public short? units_in_stock { get; set; }

    public short? units_on_order { get; set; }

    public short? reorder_level { get; set; }

    public int discontinued { get; set; }

    [ForeignKey("category_id")]
    [InverseProperty("products")]
    public virtual categories category { get; set; }

    [InverseProperty("product")]
    public virtual ICollection<order_details> order_details { get; set; } = new List<order_details>();

    [ForeignKey("supplier_id")]
    [InverseProperty("products")]
    public virtual suppliers supplier { get; set; }
}