// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

public partial class region
{
    [Key]
    public short region_id { get; set; }

    [Required]
    [StringLength(60)]
    public string region_description { get; set; }

    [InverseProperty("region")]
    public virtual ICollection<territories> territories { get; set; } = new List<territories>();
}