// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

public partial class shippers
{
    [Key]
    public short shipper_id { get; set; }

    [Required]
    [StringLength(40)]
    public string company_name { get; set; }

    [StringLength(24)]
    public string phone { get; set; }

    [InverseProperty("ship_viaNavigation")]
    public virtual ICollection<orders> orders { get; set; } = new List<orders>();
}