// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

public partial class territories
{
    [Key]
    [StringLength(20)]
    public string territory_id { get; set; }

    [Required]
    [StringLength(60)]
    public string territory_description { get; set; }

    public short region_id { get; set; }

    [ForeignKey("region_id")]
    [InverseProperty("territories")]
    public virtual region region { get; set; }

    [ForeignKey("territory_id")]
    [InverseProperty("territory")]
    public virtual ICollection<employees> employee { get; set; } = new List<employees>();
}