// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

public partial class us_states
{
    [Key]
    public short state_id { get; set; }

    [StringLength(100)]
    public string state_name { get; set; }

    [StringLength(2)]
    public string state_abbr { get; set; }

    [StringLength(50)]
    public string state_region { get; set; }
}