// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

public partial class userauths
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(100)]
    public string username { get; set; }

    [Required]
    [StringLength(100)]
    public string password_hash { get; set; }

    public bool active { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? addedon { get; set; }

    [Required]
    [StringLength(100)]
    public string addedby { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? updatedat { get; set; }

    [Column(TypeName = "character varying")]
    public string updatedby { get; set; }
}