// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace aspnetcoreapi10.Entities;

public partial class users
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(100)]
    public string name { get; set; }

    public int age { get; set; }

    public bool status { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime addedat { get; set; }

    [Required]
    [StringLength(200)]
    public string addedby { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? updatedat { get; set; }

    [StringLength(200)]
    public string updatedby { get; set; }
}